<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ikuti kami_a-engyrq7phz35</name>
   <tag></tag>
   <elementGuidId>f48cbbac-99ae-4870-9334-5b351ae30d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-engyrq7phz35']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-engyrq7phz35&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5104ce4a-294e-4634-9b8a-6824e375142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>a2f227bc-e1ea-4769-8ace-535c328b1468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>da50b94a-7274-49ac-a7fb-0654c0e98316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>c85dc8f9-852e-4fa0-8292-33849616870f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d3407539-3f21-410a-a63f-8859ee9fd29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-engyrq7phz35</value>
      <webElementGuid>038b0705-1f02-4bbd-8dde-23721a57c9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f2aa881-3791-471e-8f85-5569ad4d7843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3e1f8db0-a7c4-4003-b689-172c9c58d54f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>8051c48b-d073-435a-8899-597f5020f0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=6fl0y3rwj3z4</value>
      <webElementGuid>1754ca17-0d72-45db-9469-49982bd1ae6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r9:&quot;)/div[@class=&quot;relative flex flex-col bg-clip-border rounded-xl bg-white text-gray-700 shadow-md mx-auto w-full&quot;]/div[@class=&quot;p-6 flex justify-center&quot;]/div[@class=&quot;flex-col&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>5cc0e280-4fdb-4f78-8248-4ce1a0b3b3c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-engyrq7phz35']</value>
      <webElementGuid>3b37024c-798b-4d17-bf8a-d8759136ad3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r9:']/div/div/div/div/div/div/iframe</value>
      <webElementGuid>836f9e84-7663-40c7-bfaa-ddd8172b945b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>abb35f18-6bfa-4023-8e04-9d726a6aa3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-engyrq7phz35' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=6fl0y3rwj3z4']</value>
      <webElementGuid>51e1ba94-bf3b-4aed-9d77-23119f77e63c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
