<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_cars_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>9974f7e6-b82c-4113-bb00-712fcf6d1fef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>325e80f4-e94a-4ac8-b3cb-fc66d7f24ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>31a1f80b-df25-4813-8694-03ed5cc96e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4A5cnR5D5-V0N3GxS20PvwH7ep9naxVJR1ltsuRXKDzAiM5b4kk5jAiyDWYjSVCLFt50Cb5viRlV_PqOZeNjFdfrGtd0gr0Z6nL65CX4PRdyNwoEf1opPd87qj_gH9nceKIZOD4BTwOlC-4zcqQI1lSFxorVGfYw7GS1e4wH-wkcWUGCxQvXaPZOhjYzataEPSnRd101Wty_APDs75eBuUDwOJUg&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>b33ddbaf-8937-4cc3-809a-830b88a30ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>9dd770ff-a9f4-47c3-954f-ee3920b0569a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.12/Page_PDDikti/iframe_html1body1div11div4iframe1_c-engyrq7phz35</value>
      <webElementGuid>a506cb64-471c-4dc6-8a43-1975580cb0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>066e0803-7edf-4862-b142-dafed50278cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4A5cnR5D5-V0N3GxS20PvwH7ep9naxVJR1ltsuRXKDzAiM5b4kk5jAiyDWYjSVCLFt50Cb5viRlV_PqOZeNjFdfrGtd0gr0Z6nL65CX4PRdyNwoEf1opPd87qj_gH9nceKIZOD4BTwOlC-4zcqQI1lSFxorVGfYw7GS1e4wH-wkcWUGCxQvXaPZOhjYzataEPSnRd101Wty_APDs75eBuUDwOJUg&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[6]</value>
      <webElementGuid>a51672c6-f3d7-4920-bea9-03337d871fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>824a489b-154d-444d-a0d3-6a23bc035dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4A5cnR5D5-V0N3GxS20PvwH7ep9naxVJR1ltsuRXKDzAiM5b4kk5jAiyDWYjSVCLFt50Cb5viRlV_PqOZeNjFdfrGtd0gr0Z6nL65CX4PRdyNwoEf1opPd87qj_gH9nceKIZOD4BTwOlC-4zcqQI1lSFxorVGfYw7GS1e4wH-wkcWUGCxQvXaPZOhjYzataEPSnRd101Wty_APDs75eBuUDwOJUg&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>b8803a6f-ae0d-4b1f-a03b-be995b12fda3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
