<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>ddd02377-2cfe-40e8-99e3-b9b57e2b59ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>890184f2-5bd9-48b4-82af-49c252f01d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>731bd308-3ef7-4c92-a73d-099280f61af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4mb3_juupHOSE86gSlDdIx_s32aSPDnOfQz6D7uEQCDQMnPCJ0fuyrKAc4xvFIBhG11-8PmjgzvbXsuQ-B-Q1TutRmhZ2OxJoZE2fvO_tvr83HCLrW_d3EhOUEPnmk_AblJOoEMfOKPCNksIDCcc-Joptz2vamWW0kINqW2jK9mQ9f9Pq4iFjYuRHiqAYy1uMk1JaBQyv9iyfrmxczeDQIB-Xu1Q&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>1e8201e8-2c35-4f3f-8528-849d35af4f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>9c0ea66d-6e2f-469c-81bf-24eabd9824dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.12/Page_PDDikti/iframe_html1body1div11div4iframe1_c-engyrq7phz35</value>
      <webElementGuid>b4c589d9-5410-4848-a03a-e6f3ecd5b9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>8e0ce801-ea22-4a6b-a88a-993aad2b41b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4mb3_juupHOSE86gSlDdIx_s32aSPDnOfQz6D7uEQCDQMnPCJ0fuyrKAc4xvFIBhG11-8PmjgzvbXsuQ-B-Q1TutRmhZ2OxJoZE2fvO_tvr83HCLrW_d3EhOUEPnmk_AblJOoEMfOKPCNksIDCcc-Joptz2vamWW0kINqW2jK9mQ9f9Pq4iFjYuRHiqAYy1uMk1JaBQyv9iyfrmxczeDQIB-Xu1Q&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[2]</value>
      <webElementGuid>ec4f3cd5-d248-420c-9bc9-139a7123784c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>a32fdc9f-b2b0-40df-86a2-e6e77aff3969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4mb3_juupHOSE86gSlDdIx_s32aSPDnOfQz6D7uEQCDQMnPCJ0fuyrKAc4xvFIBhG11-8PmjgzvbXsuQ-B-Q1TutRmhZ2OxJoZE2fvO_tvr83HCLrW_d3EhOUEPnmk_AblJOoEMfOKPCNksIDCcc-Joptz2vamWW0kINqW2jK9mQ9f9Pq4iFjYuRHiqAYy1uMk1JaBQyv9iyfrmxczeDQIB-Xu1Q&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>eb4851e7-4a77-4ff2-a78b-d3a7ac579bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
