<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ikuti kami_a-6mg2tolvgddx</name>
   <tag></tag>
   <elementGuidId>433d76d7-ec53-4a94-a9c4-3b80eb7cd0b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-6mg2tolvgddx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-6mg2tolvgddx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0b445d79-5220-4b07-ac05-b20bd33a4c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>8cd960da-314f-41b6-98ea-d373a602f3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>0392482c-82a3-4fb5-8605-c304505fed51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>f48b68a4-c5ff-4ccd-be1b-6d1a429d6c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>3f52cff8-11b0-4fe2-a144-81c45f361576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-6mg2tolvgddx</value>
      <webElementGuid>29a15536-8553-4b0b-8885-fcebb9ffcd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d10e1c44-52c6-49ca-a614-5d4b4e1063d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9172d935-03dc-4906-8b12-bb78d3bf301d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>c50ca548-b83f-4be1-b04a-dcbe870bd5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=51rzsdmdo6s0</value>
      <webElementGuid>30decf40-24f0-440f-b50b-486ddca9ab3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r9:&quot;)/div[@class=&quot;relative flex flex-col bg-clip-border rounded-xl bg-white text-gray-700 shadow-md mx-auto w-full&quot;]/div[@class=&quot;p-6 flex justify-center&quot;]/div[@class=&quot;flex-col&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>1cad1878-3e2c-4e6f-ac62-31cee602c134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-6mg2tolvgddx']</value>
      <webElementGuid>1f4911a2-c650-4201-a648-adf8cfbacbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r9:']/div/div/div/div/div/div/iframe</value>
      <webElementGuid>0bdea39a-b7ea-4e87-8c33-5bc2b89b5bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0fa7eef3-0a6d-4eeb-9cc2-fbf199af1893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-6mg2tolvgddx' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=51rzsdmdo6s0']</value>
      <webElementGuid>647739f7-e09c-4238-b88a-041e2c70b6c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
