<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Perguruan Tinggi</name>
   <tag></tag>
   <elementGuidId>abba3db2-6897-42c7-8dc2-5af5e9c8a4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='material-tailwind-select-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material-tailwind-select-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>78f026b0-8a34-4c1c-879c-2bc0b2fd4e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material-tailwind-select-1</value>
      <webElementGuid>e3a2cb34-4baf-4095-8740-98d2ad819d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7e855cf2-e18d-4ec3-bfff-f47eaef0d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-[9px] pb-2 px-3 cursor-pointer select-none hover:bg-blue-gray-50 focus:bg-blue-gray-50 hover:bg-opacity-80 focus:bg-opacity-80 outline outline-0 transition-all custom-select-material-tailwind hover:text-white focus:text-white rounded-none leading-none bg-white</value>
      <webElementGuid>9fe0039c-752f-453f-8f15-76e63cd2ca32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24c7454e-6e7a-47cc-ae89-6ae843e4c2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23a125a9-32e2-4735-9981-3d0b5ef52f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fdaf4ce7-3786-4bcd-b038-60dccaff3fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perguruan Tinggi</value>
      <webElementGuid>2863365c-3d37-43dc-90ee-a20349188960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material-tailwind-select-1&quot;)</value>
      <webElementGuid>7ae0a851-8953-4d22-a6b4-499eef91c29d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='material-tailwind-select-1']</value>
      <webElementGuid>46f5dca9-ce6b-417c-9817-e49710c4a3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rc:']/li[2]</value>
      <webElementGuid>358484b3-a990-4a3b-8630-235177a2d89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[2]/following::li[1]</value>
      <webElementGuid>9917e0b3-3fca-4e27-85f6-a8e77148b0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::li[2]</value>
      <webElementGuid>4a292826-c18f-4c1e-ba6f-68322c79e5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Studi'])[1]/preceding::li[1]</value>
      <webElementGuid>fd9430cb-54f4-4fdc-953b-2455978736d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[1]/preceding::li[2]</value>
      <webElementGuid>44a8bd6e-1010-4743-bcb8-8a742c18a298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perguruan Tinggi']/parent::*</value>
      <webElementGuid>2bb1ef76-60d1-4086-ba69-6563ec9f9392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/ul/li[2]</value>
      <webElementGuid>53847066-8950-4ab8-aa7b-d9427ecd5e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'material-tailwind-select-1' and (text() = 'Perguruan Tinggi' or . = 'Perguruan Tinggi')]</value>
      <webElementGuid>2ba6689a-5650-494a-9019-7ce170dabf99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
