<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publikasi</name>
   <tag></tag>
   <elementGuidId>ced9463a-b327-4ef9-a5d0-539d0e1c1af0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='books-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#books-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31240bb3-6cfe-4541-ac70-7f8ff3e2ba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex md:col-span-2 lg:col-span-4 h-[148px] bg-white justify-center text-center items-center shadow-shadow-2 rounded-lg hover:translate-y-[-8px] ease-in-out cursor-pointer transition-all </value>
      <webElementGuid>52e1c87a-a2d8-4e64-b51b-a9aad8ed33e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>books-wrapper</value>
      <webElementGuid>6bcab16a-bf56-47fa-9250-736f67bf8a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/coming-soon</value>
      <webElementGuid>34b93490-93f9-4ffc-a0b5-b01cc6acd159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>4ba5d055-d8f8-4126-a08b-9f117e5266b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publikasi</value>
      <webElementGuid>66ac4502-3f3d-40d2-b27a-f5f87b17012b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full px-3 mt-[-40px]&quot;]/div[@class=&quot;max-w-7xl mt-10 flex justify-center items-center mx-auto&quot;]/div[@class=&quot;w-full grid grid-cols-1 md:grid-cols-4 lg:grid-cols-8 justify-center items-center gap-5&quot;]/a[@id=&quot;books-wrapper&quot;]</value>
      <webElementGuid>18aceb51-dffe-4888-9a17-2bf5afaf3ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='books-wrapper']</value>
      <webElementGuid>33a7d640-31d7-4e61-b33e-87375db16472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div[2]/div/a[3]</value>
      <webElementGuid>a67f9ea5-70e7-4940-a3a9-6d698893961b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[3]</value>
      <webElementGuid>46b1b98c-f3d7-4a41-b6e4-17a2c2264f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::a[3]</value>
      <webElementGuid>f2c48d06-f1da-4d13-92ce-c7fe0dc352a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada kendala terkait data Pendidikan Tinggi?'])[1]/preceding::a[3]</value>
      <webElementGuid>e6d7d788-64c4-4879-9d1e-6e700d5e86c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::a[3]</value>
      <webElementGuid>503afa75-c690-48e3-a264-201a399ee235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/coming-soon')]</value>
      <webElementGuid>8704aa26-3082-48ba-9869-8dde530c7670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>e05bb71f-b779-403e-8619-58e731f47622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'books-wrapper' and @href = '/coming-soon' and (text() = 'Publikasi' or . = 'Publikasi')]</value>
      <webElementGuid>54ddb98b-80f7-47bd-b913-159e5251e30c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
