<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>bc4eabc4-f7c2-40dd-9030-b1d13447ee33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ad38e5e-8908-4c5f-a121-0ca6d85e81ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>60230a71-bf1c-4e2f-8201-dfc115f4845e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4gNkkLORczxFIGyn6f2iyT1DnZkw684AxAmJ5fQ7Mi8OCKIb3tXIswR1nNrJCDK4_AdHfsMaZK7eamAmLNO-gX_XZGlpAL5-RylT1vOq3SXa7X76Iq5cFvbVf8nL9AtINa3OpoeiyR5xVJDtjCrFCnJKKI_MLcNhMJJH_fUyxs7nN31y-PovotKl028V5NiMxSztli4aCT3tYdIbtMaVROi3hXoA&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>eedf7802-3eec-41dc-a9d4-7f1214b93e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>b5c3da8c-bce0-4edd-9ee4-d1830b91839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.09a/Page_PDDikti/iframe_html1body1div11div4iframe1_c-ywfblivavfuo</value>
      <webElementGuid>942fde88-386f-4cc6-90a4-7d7e7f3ed575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      <webElementGuid>c5fb6e35-7a73-4a74-b83b-4e25dbfc8338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4gNkkLORczxFIGyn6f2iyT1DnZkw684AxAmJ5fQ7Mi8OCKIb3tXIswR1nNrJCDK4_AdHfsMaZK7eamAmLNO-gX_XZGlpAL5-RylT1vOq3SXa7X76Iq5cFvbVf8nL9AtINa3OpoeiyR5xVJDtjCrFCnJKKI_MLcNhMJJH_fUyxs7nN31y-PovotKl028V5NiMxSztli4aCT3tYdIbtMaVROi3hXoA&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')]</value>
      <webElementGuid>35e16acf-cac6-4a90-b21b-bb91ff5df5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a5ad20a5-a9b1-4cee-af9b-c87b0efba391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4gNkkLORczxFIGyn6f2iyT1DnZkw684AxAmJ5fQ7Mi8OCKIb3tXIswR1nNrJCDK4_AdHfsMaZK7eamAmLNO-gX_XZGlpAL5-RylT1vOq3SXa7X76Iq5cFvbVf8nL9AtINa3OpoeiyR5xVJDtjCrFCnJKKI_MLcNhMJJH_fUyxs7nN31y-PovotKl028V5NiMxSztli4aCT3tYdIbtMaVROi3hXoA&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>a94d637d-5235-43c5-9131-619b23985560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
