<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Perguruan Tinggi</name>
   <tag></tag>
   <elementGuidId>b031d2b4-8e7a-4f67-ae8e-269d2e71cc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buildings-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buildings-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97280a12-c0ca-4e2a-95b0-782bfa3bdb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex md:col-span-2 lg:col-span-4 h-[148px] bg-white justify-center text-center items-center shadow-shadow-2 rounded-lg hover:translate-y-[-8px] ease-in-out cursor-pointer transition-all </value>
      <webElementGuid>fd4284ec-1c51-4d59-9859-99932978b630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildings-wrapper</value>
      <webElementGuid>b36af1c8-0cfa-45a4-a6a9-b924b5c221db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/perguruan-tinggi</value>
      <webElementGuid>b3a86f99-1a84-4c7f-8ca4-4537d9a777c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>11402c69-ef5b-485a-bc51-d465cdde93d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perguruan Tinggi</value>
      <webElementGuid>2913a839-2b13-4df5-8795-9399d1689fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full px-3 mt-[-40px]&quot;]/div[@class=&quot;max-w-7xl mt-10 flex justify-center items-center mx-auto&quot;]/div[@class=&quot;w-full grid grid-cols-1 md:grid-cols-4 lg:grid-cols-8 justify-center items-center gap-5&quot;]/a[@id=&quot;buildings-wrapper&quot;]</value>
      <webElementGuid>422dda55-85d6-4a87-946b-717045122258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buildings-wrapper']</value>
      <webElementGuid>9a54231a-e3be-466d-965d-a292ae8549b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div[2]/div/a[2]</value>
      <webElementGuid>5bca0271-3d61-4201-b21e-4faa6bcbdf68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[2]</value>
      <webElementGuid>4fe7a50e-dd4d-431f-bdb3-5c6be46dc527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::a[2]</value>
      <webElementGuid>c37670c4-d498-420c-995c-2a6700829db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada kendala terkait data Pendidikan Tinggi?'])[1]/preceding::a[4]</value>
      <webElementGuid>8d1dd0e6-b7e8-4317-bc13-6dd15fb4e996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::a[4]</value>
      <webElementGuid>17ff8370-1935-4a0c-a5c7-2fb6c9d060b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/perguruan-tinggi')]</value>
      <webElementGuid>bbde0916-943b-46e6-997c-ec0504f0ae5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>debad429-2ff3-4bd1-a396-ee120a3f08ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buildings-wrapper' and @href = '/perguruan-tinggi' and (text() = 'Perguruan Tinggi' or . = 'Perguruan Tinggi')]</value>
      <webElementGuid>98898693-3d6e-47bd-aa46-988ee80878c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
