<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ec1f516d-3a0b-4404-ba4b-696708675f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[5]/div/div/div/div/div/button/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Dropdown Arrow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ea38d3d-c720-45d9-a610-6a7600dca09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/dropdown.954bafd62ce6e61bf71a06ed92a460d2.svg</value>
      <webElementGuid>13b19823-20f0-4eef-87ce-170bfda54fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Dropdown Arrow</value>
      <webElementGuid>e0c486a4-1bb9-4db5-a007-d7413c1c8a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full px-3 mt-[-40px]&quot;]/div[@class=&quot;max-w-7xl flex justify-center mx-auto&quot;]/div[@class=&quot;px-1 md:px-6 lg:px-16 md:w-11/12 w-full&quot;]/div[@class=&quot;flex shadow-shadow-2 rounded-2xl custom-ul-material-tailwind&quot;]/div[@class=&quot;custom-width-material-tailwind rounded-s-2xl relative hidden flex-row items-center justify-center md:flex w-1/5 bg-gradient-to-r from-linear-1-1 to-linear-1-2 cursor-pointer focus:outline-none border-none&quot;]/div[@class=&quot;relative w-full min-w-[200px] h-10&quot;]/button[@class=&quot;peer w-full h-full bg-transparent text-left outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all border px-3 py-2.5 rounded-[7px] border-[var(--orange)] rounded-[var(--secondary-select)] pb-[42px] text-lg font-medium font-inter text-black border-none focus:border-none active:border-none cursor-pointer outline-none&quot;]/div[@class=&quot;grid place-items-center absolute top-2/4 right-2 pt-px w-5 h-5 text-blue-gray-400 rotate-0 -translate-y-2/4 transition-all&quot;]/img[1]</value>
      <webElementGuid>7d512fc0-7f2f-4ff4-8eec-53ce13b5fa8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div/div/div/div/div/button/div/img</value>
      <webElementGuid>0a0c10a0-7f86-4049-afda-f6feba43df04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Dropdown Arrow']</value>
      <webElementGuid>662bc0f9-e2f0-4098-b9a7-523fba273984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/img</value>
      <webElementGuid>dd06c387-6c8b-4068-ab7a-6537cf093efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/dropdown.954bafd62ce6e61bf71a06ed92a460d2.svg' and @alt = 'Dropdown Arrow']</value>
      <webElementGuid>716677fe-6d46-4307-832b-2de132632c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
