<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Program Studi</name>
   <tag></tag>
   <elementGuidId>f1b4df7a-919e-44ef-a92a-0c09df497f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='material-tailwind-select-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material-tailwind-select-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4cda0878-e2d0-4fa7-b175-368245eba2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material-tailwind-select-2</value>
      <webElementGuid>db3ad97a-23b5-4942-b880-f5de2ec40d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>309a2742-a60a-4720-b731-886cf0bdac00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-[9px] pb-2 px-3 cursor-pointer select-none hover:bg-blue-gray-50 focus:bg-blue-gray-50 hover:bg-opacity-80 focus:bg-opacity-80 outline outline-0 transition-all custom-select-material-tailwind hover:text-white focus:text-white rounded-none leading-none bg-white</value>
      <webElementGuid>5c362302-696f-403e-9f04-d37828fdb05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>30f2f018-f97f-459e-a876-833377639638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9c1bccc-0785-4268-bd2a-0418439bca9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8d27a4f-c3f3-44b7-9d2d-6e3b923d41c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program Studi</value>
      <webElementGuid>3bd89ff8-8050-45a9-a7d6-1b9fc9aaa18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material-tailwind-select-2&quot;)</value>
      <webElementGuid>a0f526c4-439e-4f3e-bdee-fc74adf1e41c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='material-tailwind-select-2']</value>
      <webElementGuid>427d3ebe-3ae9-4093-8685-7aae54d7d756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rc:']/li[3]</value>
      <webElementGuid>dee533a9-8e49-44c3-b636-2083b89020b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perguruan Tinggi'])[2]/following::li[1]</value>
      <webElementGuid>b1134a6b-9624-4e39-85a3-38596de080ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::li[2]</value>
      <webElementGuid>14f5228f-c391-47d5-b868-bf6e404f0651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[1]/preceding::li[1]</value>
      <webElementGuid>c247b931-e62c-40fb-8e24-69eeece27544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahasiswa'])[1]/preceding::li[2]</value>
      <webElementGuid>3ca8e4b7-0eeb-47ae-863a-01a34f4cf170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program Studi']/parent::*</value>
      <webElementGuid>c1f92b04-836b-4b64-b0a9-de77946d5f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>8436fd12-22ba-4b87-b7b3-e3e971036aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'material-tailwind-select-2' and (text() = 'Program Studi' or . = 'Program Studi')]</value>
      <webElementGuid>0cff5642-0702-4a7d-9fc8-a90a030816d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
