<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Perguruan Tinggi</name>
   <tag></tag>
   <elementGuidId>9edcee4f-41f9-4887-8865-64c8634bd6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='material-tailwind-select-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#material-tailwind-select-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cb2b2d0d-339a-4b26-8934-c8b560c7c74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>material-tailwind-select-1</value>
      <webElementGuid>c1cb9169-8015-4d6e-b0fe-c8d9193190bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d76a87df-6b2d-43bc-8b07-bd47e979270b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pt-[9px] pb-2 px-3 cursor-pointer select-none hover:bg-blue-gray-50 focus:bg-blue-gray-50 hover:bg-opacity-80 focus:bg-opacity-80 outline outline-0 transition-all custom-select-material-tailwind hover:text-white focus:text-white rounded-none leading-none bg-white</value>
      <webElementGuid>879a12d8-9dfa-4f7c-a3d5-779783d70571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fada1d08-4fae-4c22-910b-9b3e682b38bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b31fbc9c-2f63-43bd-a215-67829ea8b9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>452d94b3-f9ba-4782-9c5a-c1a100ff02ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Perguruan Tinggi</value>
      <webElementGuid>0d8b9a82-f811-4f8c-8ac8-bf6013d2d983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;material-tailwind-select-1&quot;)</value>
      <webElementGuid>e9abbf57-26ab-47f0-9d08-9971abbba07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='material-tailwind-select-1']</value>
      <webElementGuid>d8bc79fd-eadf-4ca6-a40e-dfdd94c45c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id=':rc:']/li[2]</value>
      <webElementGuid>c022fd3a-9430-4baa-b0ec-caf2b555046a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[2]/following::li[1]</value>
      <webElementGuid>3e496a37-1bc1-4b5f-babf-842400aa60d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::li[2]</value>
      <webElementGuid>933d1d31-5d88-45b1-bf28-65de7bc0705c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Studi'])[1]/preceding::li[1]</value>
      <webElementGuid>2c63e6bc-9153-4721-9926-49f24a2e7aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[1]/preceding::li[2]</value>
      <webElementGuid>ecdeb8ab-ef05-4bfd-9ac4-47f2721b7771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Perguruan Tinggi']/parent::*</value>
      <webElementGuid>abb60dcb-1e03-4a69-a598-941deb25ccb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/ul/li[2]</value>
      <webElementGuid>4c1a74f1-ad88-4c7c-8b65-e69cd35c702b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'material-tailwind-select-1' and (text() = 'Perguruan Tinggi' or . = 'Perguruan Tinggi')]</value>
      <webElementGuid>fb4361a0-3c6f-4236-91a9-21d878111108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
