<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasil Pencarian Semua</name>
   <tag></tag>
   <elementGuidId>63d35a4d-7257-4341-b7fd-4ed3e9fdf068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>226d9026-6b9d-4766-829c-c1472b476cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-heading-s sm:text-heading-m font-semibold</value>
      <webElementGuid>13ae49d8-1cf7-4d11-86cb-db3c9193cd71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasil Pencarian Semua</value>
      <webElementGuid>cf0f5e3f-ff92-4bd1-9ed3-c76f1826a13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full p-3&quot;]/div[@class=&quot;mx-auto items-center justify-center max-w-7xl flex py-3 undefined&quot;]/div[@class=&quot;w-full lg:p-[32px] md:p-[16px] p-3 bg-linear-main shadow-inner-shadow-1 rounded-md text-neutral-10  bottom-0&quot;]/div[@class=&quot;text-heading-s sm:text-heading-m font-semibold&quot;]</value>
      <webElementGuid>1b059f0b-13e5-49b8-bcff-faa5d7ed87aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[2]/div/div[2]</value>
      <webElementGuid>406aa81a-16a0-420d-9082-e54883dc34f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Pencarian'])[1]/following::div[4]</value>
      <webElementGuid>a18ec7c1-0a87-43cf-a4c5-6b6518f61755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::div[4]</value>
      <webElementGuid>d7edb73d-7491-4340-8e94-19bceece5a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::div[2]</value>
      <webElementGuid>b053ba50-c47e-4d1e-b627-5ef9d1bf7df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[1]/preceding::div[3]</value>
      <webElementGuid>e756bc04-3864-439e-b514-7563eedf5b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hasil Pencarian Semua']/parent::*</value>
      <webElementGuid>0914a8de-16ff-4647-b1c8-399d28823041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>4d96e164-214d-45b2-bf3b-16f69c9ca6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hasil Pencarian Semua' or . = 'Hasil Pencarian Semua')]</value>
      <webElementGuid>80e30405-6412-4879-8646-add405d5f553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[2]/div</value>
      <webElementGuid>e10e3a78-9526-4aa1-8157-a85ad3d5f8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Pencarian'])[1]/following::div[2]</value>
      <webElementGuid>b8bdb482-f303-4327-8f83-3e4e8d20aaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::div[2]</value>
      <webElementGuid>07835f2d-09b7-4c41-80f8-b99cc45c56f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::div[4]</value>
      <webElementGuid>d4278604-6759-4802-9274-cd598b603313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>a29192d3-5f6b-4f3b-a892-84562d7ce946</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
