<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DosenNamaPerguruan TinggiProgram StudiAksiHENDRAWATIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFIRMANENIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARDIYAHAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat Detail</name>
   <tag></tag>
   <elementGuidId>1295ddd2-4215-4941-ab49-038d8e79e544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65d7dc90-8742-4516-bd8d-a3bdca7a2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:p-[32px] md:p-[16px] py-2 bg-white shadow-inner-shadow-1 rounded-md w-full bottom-0</value>
      <webElementGuid>96235983-81e2-4791-84c3-b601906f1864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DosenNamaPerguruan TinggiProgram StudiAksiHENDRAWATIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFIRMANENIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARDIYAHAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailANFERI DEVINRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailAGUS RIZALAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFEBRIA SYAFYUSARIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARIZA ELVIRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailVETRI NATHALIAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailNOVITA ANGGRAINIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailARIA SUSANTIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat Detail1 dari10</value>
      <webElementGuid>c15c8035-63b1-416c-971c-298fe2e145d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full p-3&quot;]/div[@class=&quot;mx-auto items-center justify-center max-w-7xl flex my-10 relative z-10&quot;]/div[@class=&quot;lg:p-[32px] md:p-[16px] py-2 bg-white shadow-inner-shadow-1 rounded-md w-full bottom-0&quot;]</value>
      <webElementGuid>914aee4b-a941-4a95-9a8f-cb06fd46ffa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div[4]/div</value>
      <webElementGuid>d7c80684-b562-412c-b35e-b7757315951e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::div[2]</value>
      <webElementGuid>569bbb8d-59f4-4c3c-9186-7e411f28e6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Pencarian Semua'])[1]/following::div[4]</value>
      <webElementGuid>2ede4f4d-b1e7-4f2d-b202-812f405d782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div</value>
      <webElementGuid>0a66c4a3-a440-431d-94f3-61c6c2de91c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DosenNamaPerguruan TinggiProgram StudiAksiHENDRAWATIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFIRMANENIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARDIYAHAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailANFERI DEVINRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailAGUS RIZALAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFEBRIA SYAFYUSARIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARIZA ELVIRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailVETRI NATHALIAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailNOVITA ANGGRAINIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailARIA SUSANTIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat Detail1 dari10' or . = 'DosenNamaPerguruan TinggiProgram StudiAksiHENDRAWATIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFIRMANENIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARDIYAHAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailANFERI DEVINRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailAGUS RIZALAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailFEBRIA SYAFYUSARIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailMARIZA ELVIRAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailVETRI NATHALIAAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailNOVITA ANGGRAINIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat DetailARIA SUSANTIAKADEMI KEPERAWATAN NABILAKEPERAWATANLihat Detail1 dari10')]</value>
      <webElementGuid>62a6c861-1f35-49aa-a67f-595d610d0ece</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
