<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ikuti kami_a-ex73o5fwtwg7</name>
   <tag></tag>
   <elementGuidId>013d5499-4f97-4f59-8c01-46da47213434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-ex73o5fwtwg7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-ex73o5fwtwg7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>79034d59-74a5-414b-847d-b24eac17793f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4c7aa66b-c87b-44de-badd-454fcd5d2344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ca60f8f0-4d0c-429c-8c42-7387e8f3d62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>347964c3-84b8-4be9-8047-04135f9110c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>1d2fc56b-1169-4b6a-82e1-b151f3d8e2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ex73o5fwtwg7</value>
      <webElementGuid>340d2ad3-0ec1-45f6-8ce1-fff65897f40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1025485-52ac-4adc-8bec-d4e2400949af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>69f65042-ef1c-4494-a4f2-ba84c1e9f418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>03f81f92-97d0-4ecc-9033-8a100caf2e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=btuijhf4k579</value>
      <webElementGuid>66c5c9d4-acfe-4f73-9535-a22729964add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r9:&quot;)/div[@class=&quot;relative flex flex-col bg-clip-border rounded-xl bg-white text-gray-700 shadow-md mx-auto w-full&quot;]/div[@class=&quot;p-6 flex justify-center&quot;]/div[@class=&quot;flex-col&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>e926c2aa-b20f-4ec1-b721-d4f2e04d3a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-ex73o5fwtwg7']</value>
      <webElementGuid>f4a5ad9f-a7fd-45ed-ab26-36801cd4f798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r9:']/div/div/div/div/div/div/iframe</value>
      <webElementGuid>7a727f7b-b7d1-46ee-8be8-6d6b97d73cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>026fff92-154a-4f1d-908a-8cf318c175a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-ex73o5fwtwg7' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=btuijhf4k579']</value>
      <webElementGuid>ce0cc34f-ef6b-4ade-b5a1-cc519667a434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
