<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div11div4iframe1_c-ex73o5fwtwg7</name>
   <tag></tag>
   <elementGuidId>92d1081d-3865-4bcc-8fed-1d6880fb8304</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-ex73o5fwtwg7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-ex73o5fwtwg7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7ea08ed1-fd24-4cdd-8024-6ca886221b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>e1d504d3-b6b1-4c0b-856e-a50f69461309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-ex73o5fwtwg7</value>
      <webElementGuid>254236bb-22e4-4394-b59c-8a04c6726df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>69ca6274-59b2-4053-9117-f1859b58e6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1f25b3dc-6725-48d7-bd58-44b58209a3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>9989801d-5690-4d12-b830-f6935cf2c4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>8066a2ca-0031-411b-b420-c781cda06d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[11]/div[4]/iframe[1]</value>
      <webElementGuid>ce1a0b67-6e3f-4b94-ab23-28c2ea1b6777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-ex73o5fwtwg7']</value>
      <webElementGuid>145b2031-a551-469b-9656-61df007c9aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>2cc58ccc-034d-463b-880a-cc0c5cb1f091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-ex73o5fwtwg7' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>ac126c38-f291-49b8-91e1-15bb693a1449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
