<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click verify once there are none left_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>a731a8dd-244d-47b0-8574-53268bb5cea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ffc12997-f638-44c5-b91f-508c6aacce0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>9a68b6a7-378a-4f4a-a657-c907084ab5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6LELxiNJ5F0RPee-kVCPY6iKpKMO6cGcxulpkGvU9H7NWqJZ3qXoJGQhhpeiqqLkFnjvKfQGXClpdQFRLIGG42FoqFjdgCY8T04MydhQg8IXty97G2V4WiPF8vVAg0vcB8QAyKp437oWieYaaDZvbkN73FVos30JOBqpBHMC9UPUoYX5wlyBkpcSuj9UEiqSvtnRht5PUoseLxFdT0X4PJQsoHOQ&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>9425c702-84ff-4b16-9819-1772d3282095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>081d01b3-a090-4269-a184-015725a246cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti_001_05/Page_PDDikti/iframe_html1body1div11div4iframe1_c-ex73o5fwtwg7</value>
      <webElementGuid>4b4a488e-1f30-4303-a98b-ce0e5b6d6b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>5102b450-161b-4472-b6c9-a272080805c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6LELxiNJ5F0RPee-kVCPY6iKpKMO6cGcxulpkGvU9H7NWqJZ3qXoJGQhhpeiqqLkFnjvKfQGXClpdQFRLIGG42FoqFjdgCY8T04MydhQg8IXty97G2V4WiPF8vVAg0vcB8QAyKp437oWieYaaDZvbkN73FVos30JOBqpBHMC9UPUoYX5wlyBkpcSuj9UEiqSvtnRht5PUoseLxFdT0X4PJQsoHOQ&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[3]</value>
      <webElementGuid>b3cd59ac-4c6b-4eea-b398-df07befa3d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>4b7bb5d9-343f-4312-bd1c-bbd03923f0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6LELxiNJ5F0RPee-kVCPY6iKpKMO6cGcxulpkGvU9H7NWqJZ3qXoJGQhhpeiqqLkFnjvKfQGXClpdQFRLIGG42FoqFjdgCY8T04MydhQg8IXty97G2V4WiPF8vVAg0vcB8QAyKp437oWieYaaDZvbkN73FVos30JOBqpBHMC9UPUoYX5wlyBkpcSuj9UEiqSvtnRht5PUoseLxFdT0X4PJQsoHOQ&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>7dfd4c07-3fd3-4ee9-bc23-32dc7da65a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
