<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Publikasi</name>
   <tag></tag>
   <elementGuidId>3a3d0be2-34ab-4c35-9ee9-a5006614cb75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='books-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#books-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a6611a2-8bc5-4e04-aab4-153cd0f1cd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex md:col-span-2 lg:col-span-4 h-[148px] bg-white justify-center text-center items-center shadow-shadow-2 rounded-lg hover:translate-y-[-8px] ease-in-out cursor-pointer transition-all </value>
      <webElementGuid>cc1af582-d5bf-4aa8-8ae5-f91929afa429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>books-wrapper</value>
      <webElementGuid>50cd2b31-8325-4774-bf11-9417dcc20c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/coming-soon</value>
      <webElementGuid>ace70880-8ad0-46e6-9fed-d6e8d70ddc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>2eed4821-e001-454d-9fb2-81a4855cf9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publikasi</value>
      <webElementGuid>2157feee-9f41-4d4f-90d4-035bf5e55d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full px-3 mt-[-40px]&quot;]/div[@class=&quot;max-w-7xl mt-10 flex justify-center items-center mx-auto&quot;]/div[@class=&quot;w-full grid grid-cols-1 md:grid-cols-4 lg:grid-cols-8 justify-center items-center gap-5&quot;]/a[@id=&quot;books-wrapper&quot;]</value>
      <webElementGuid>d79439be-1328-40e9-afef-149eb35da113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='books-wrapper']</value>
      <webElementGuid>b04e6c85-e251-46fe-8abf-8d398e37c80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div[2]/div/a[3]</value>
      <webElementGuid>b9418ad5-b689-42ff-8abb-db62e1dcb7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua'])[1]/following::a[3]</value>
      <webElementGuid>565713c6-c0a2-4556-8701-72899db89666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::a[3]</value>
      <webElementGuid>9907bbcf-2f9c-4232-91d2-ec849d7e49f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada kendala terkait data Pendidikan Tinggi?'])[1]/preceding::a[3]</value>
      <webElementGuid>feedd260-670d-449b-af24-2bc6e7d7c55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='di sini'])[1]/preceding::a[3]</value>
      <webElementGuid>6ffd2619-3221-49a5-9334-f0130207f653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/coming-soon')]</value>
      <webElementGuid>b7d07436-b0ac-48ac-afe2-c5df7e20098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>2088eb34-d5a1-4310-98f0-30979fbbe22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'books-wrapper' and @href = '/coming-soon' and (text() = 'Publikasi' or . = 'Publikasi')]</value>
      <webElementGuid>8f6ec5c3-3d22-426b-ac37-1d2052ea0fcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
