<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coming Soon</name>
   <tag></tag>
   <elementGuidId>a3ddfbc1-0172-49d9-af87-a8e86fd5e9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mx-auto.items-center.justify-center.max-w-7xl.flex.py-3.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>512bea74-029b-4a2a-b672-582fa2ede460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto items-center justify-center max-w-7xl flex py-3 undefined</value>
      <webElementGuid>f4aedfab-7373-432c-ae33-1a4629a28287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coming Soon</value>
      <webElementGuid>1f5a3a3e-2a07-40d8-ab52-94d3d0c8e1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;w-full px-6  mt-[120px]&quot;]/div[@class=&quot;mx-auto items-center justify-center max-w-7xl flex py-3 undefined&quot;]</value>
      <webElementGuid>10f7eaaa-4da4-4cac-8d69-38ddb2261105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div</value>
      <webElementGuid>ce2a5697-b633-4cf1-bb5e-37bb1e2d7fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::div[2]</value>
      <webElementGuid>272d107e-3d73-42ca-bcd0-9dfb35438ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang PDDikti'])[1]/following::div[2]</value>
      <webElementGuid>847f287e-d381-42ac-a36c-da051c901209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke Beranda'])[1]/preceding::div[4]</value>
      <webElementGuid>9fdcb2e3-ae91-4654-ac94-3d91970a8059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>409802a7-19ae-4f9a-b5c0-a62797678feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Coming Soon' or . = 'Coming Soon')]</value>
      <webElementGuid>fcafe94a-fe0f-4e66-8a0f-3a587c280934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
