<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</name>
   <tag></tag>
   <elementGuidId>dc567cab-ff20-404d-ba26-364322e0ea4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-r44b62qr6lqc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-r44b62qr6lqc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dc1ad296-9342-467c-8da5-e2c8febf4b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>954de70c-180a-40b9-aa0c-59670b15a268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-r44b62qr6lqc</value>
      <webElementGuid>6845732d-52e1-4c63-9382-544711b102eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>02dcc65b-ee16-450a-8c45-935638ab9033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f9d884d3-c20b-4ffa-b767-7e5a9af793d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>b4bc0624-595a-4dd0-9b0f-7b5e5b1e137e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>3095ef17-f1de-48b7-8a06-b0278d81668f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[11]/div[4]/iframe[1]</value>
      <webElementGuid>bb5dcc7d-c04f-40d0-9b98-ef2dcf443979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-r44b62qr6lqc']</value>
      <webElementGuid>6e127ed3-1698-434c-9063-cf736527285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>6780ae3d-306a-4aac-8790-adb016776791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-r44b62qr6lqc' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>d51c860d-14f4-4086-b3a0-85c7f6a510c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
