<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Ikuti kami_a-r44b62qr6lqc</name>
   <tag></tag>
   <elementGuidId>c0a79c0b-e1db-4264-9ec6-55dd1cf09207</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-r44b62qr6lqc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-r44b62qr6lqc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>18e328ce-88a3-4e06-b35c-9e3171ad6573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>c5c08fb3-04d4-42c4-aa74-8d34c448d886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>702d4ddf-4e2b-4737-bd47-e50fb2360ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>1af92fca-54e6-4a14-93b6-ef458921a502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>9793d534-f457-4925-911b-17d3d5f47182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-r44b62qr6lqc</value>
      <webElementGuid>2dc8fdae-1ba5-45f4-a024-d645984eae57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f85566f-60b8-4039-89de-44fcd04711b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9d0a8e77-7ac9-4cb0-ba33-0da8087e8e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>2c9acdcb-a8ee-4483-b55a-00462bdad0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=5ig6lbxarq8u</value>
      <webElementGuid>908ac28a-5fe1-482c-908e-ce5df7965ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r9:&quot;)/div[@class=&quot;relative flex flex-col bg-clip-border rounded-xl bg-white text-gray-700 shadow-md mx-auto w-full&quot;]/div[@class=&quot;p-6 flex justify-center&quot;]/div[@class=&quot;flex-col&quot;]/div[1]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>207f9e25-241f-4721-894e-7f2a440f5784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-r44b62qr6lqc']</value>
      <webElementGuid>fdf1eade-5254-4d2c-b23a-e3bca72dd395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r9:']/div/div/div/div/div/div/iframe</value>
      <webElementGuid>010d2ce2-58cb-4e0e-ae33-7008b02f82a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7c4e72cf-d604-430d-820b-8972e9fd1794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-r44b62qr6lqc' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;co=aHR0cHM6Ly9wZGRpa3RpLmtlbWRpa2J1ZC5nby5pZDo0NDM.&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;size=normal&amp;cb=5ig6lbxarq8u']</value>
      <webElementGuid>c9a54362-3b1b-41f2-8d38-d8433d09d415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
