<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>a9852adf-bca6-4f73-a400-d61668f8b873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>95438983-9106-46d9-9f77-032469a8d701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>bdf66961-7952-4d7a-86e7-b4fecb1b552b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2</value>
      <webElementGuid>7b540df4-3d7a-4901-84f4-e20de4941853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>1ba40fb4-4d53-4089-9e1a-fa7a59fd15b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.18/Page_PDDikti/iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</value>
      <webElementGuid>6c341b7d-64c7-46be-8a7f-d8613c1ed3b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>8b9d8dc4-5d28-485f-a7a6-4c0bb75d60af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2')])[2]</value>
      <webElementGuid>4d244770-fa05-40f6-bc48-d7b2f98e2704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>0d969ba3-0c3b-48b8-a746-3136224caa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2']</value>
      <webElementGuid>021b985e-2176-4f2e-859f-fe69e9425821</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
