<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>10b913fe-0bca-4941-9016-675b233f3575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13d20877-f41b-41b0-80af-72574f61d5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>29f71d88-17a3-4e06-81da-14843dfbf879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>0fe96779-77fa-4033-9d68-8b0723b0c5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b67e0c81-3083-4511-b6be-ace8483514c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.18/Page_PDDikti/iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</value>
      <webElementGuid>cbf3f0ce-411d-4906-bf55-fb5cc9c75b8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      <webElementGuid>fb1727ca-cd2c-475f-9c0b-d551f69ea425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[14]</value>
      <webElementGuid>49ba6265-c4e3-478d-b1f6-2f392d6ebd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/img</value>
      <webElementGuid>2dc3bf77-f373-4eeb-91d4-8a5fcf4bfd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>0c80b2f3-214f-4f6a-84c2-d6c07e96dd72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
