<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>d9d91bc3-34a1-46ed-9190-934c878c3f17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cddb57eb-8263-469c-9d5e-987fe39f7c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>9aa2a115-7228-43b4-9f1d-21a3133f2731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>a1d8afcb-832b-4d1f-9f6a-0ae11cd45356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>3c3401be-fe4d-4441-84a4-a56ec4491419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.18/Page_PDDikti/iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</value>
      <webElementGuid>2d4efd0b-321f-4345-83d1-5b8b2931defc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>4d88e45c-46ff-4211-ac5d-aa61e453a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[6]</value>
      <webElementGuid>081d70d3-bf51-4506-815f-7c5e791d8c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>4a469a5c-337d-4bb2-812d-bebb2f06a5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA72Ylo16XPk3dOk9IoJAtEjdAOlsvb06Jgx6RMb4QkXL2-T6fj2HgQb4ADCfz_q1nka-QNNzNDWFC5ZOYk1ydZyimwy5MdrxqY7tLzhJqVHf9elxQopf78eopLmc8ysDToj-q8DepHNE3ZiXuJxtm-dkp5vIHgcqEcBt-mNj4B4K77eAlZTGUIJL1sx80E5uWh24XX-&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>90e6f682-4541-4422-a7a5-84e892caa138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
