<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_If there are none, click skip_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>65886379-f58a-4d0e-b6f9-1bf7286034f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c2911705-8cc4-47f3-89af-4eba5df5274f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>e1d8d971-2aa2-4df6-b94f-d6b4e92b40a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2</value>
      <webElementGuid>d0e7696b-241d-470c-bfba-9f3c33ca256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>3e0cb8d7-daa0-4e2a-8c87-5e9d6e25316d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.18/Page_PDDikti/iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</value>
      <webElementGuid>9ddecd4c-621f-423b-b3b2-e32ff7462113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>ab03e249-bff7-4fc8-87b6-c0b895e3d971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2')])[6]</value>
      <webElementGuid>fb2543a1-ef58-4f1e-a6b4-4d0f21a1f2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>08e7e6e0-b0ba-4e8c-a65d-cb8a174403a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6Oy0ai8hg57eNdrzsaqa2Dm57rccNq2tBVbi4lE3iLNE0PLsO9cvvcsArbVx0hSlYNuGdWxDthO0vPdpq7TLb1WZfxZrQUU6rOw1EbTMraMuk9d8EGvwhZPI_0t1Yzx8iVdqnrIRh64aOzOL82JtAnzEV5d7kal5_u7V_QuEGzGwghiHZeppcjxbz9ZGC4b2cDDgdR&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD&amp;id=2']</value>
      <webElementGuid>354c826c-e1f0-43c2-9858-491935d7fd37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
