<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bridges_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>bae3d0bf-327a-45ee-8f7a-a2497971b408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4a5d961-7f5a-4978-a8d6-16f5d23ba363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>2d41dfdf-3cef-4935-b8f7-fe39ae12f4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7c4_hYmDS2t86ksVmkX2ErT90uQ4Qd7DixE7QTXRGJpU3b1_u0hQUForZmOaJzcOtKUmyloI3D2sjF2Jh8Z0DXCrhuADSHYkCD25wsKvGQOJx3alYlT-mLjluwYATFUFKVCvg0x3uJt6fl6mX2Wsa6fO8Dyhuyu47PjB8nWhqtQ-rmSr95ZzeHVeOV-GMKL_ZPwu3J&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD</value>
      <webElementGuid>fd1d9ee0-7c9b-4076-8b66-5f2cc6dea003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>88151d27-d606-4763-884f-a362360e4efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/TC_PDDikti.001.18/Page_PDDikti/iframe_html1body1div11div4iframe1_c-r44b62qr6lqc</value>
      <webElementGuid>c51f3bbf-8e87-4f13-b8a5-ed296ef1e778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      <webElementGuid>bfb67e3e-ffc6-4f5f-b093-3e26d44e8577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7c4_hYmDS2t86ksVmkX2ErT90uQ4Qd7DixE7QTXRGJpU3b1_u0hQUForZmOaJzcOtKUmyloI3D2sjF2Jh8Z0DXCrhuADSHYkCD25wsKvGQOJx3alYlT-mLjluwYATFUFKVCvg0x3uJt6fl6mX2Wsa6fO8Dyhuyu47PjB8nWhqtQ-rmSr95ZzeHVeOV-GMKL_ZPwu3J&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD')])[2]</value>
      <webElementGuid>669e3b7b-1f58-42b1-9984-c8f9de2efd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
      <webElementGuid>9c0dca38-2ee6-4ce4-b99a-4d6ab5347001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA7c4_hYmDS2t86ksVmkX2ErT90uQ4Qd7DixE7QTXRGJpU3b1_u0hQUForZmOaJzcOtKUmyloI3D2sjF2Jh8Z0DXCrhuADSHYkCD25wsKvGQOJx3alYlT-mLjluwYATFUFKVCvg0x3uJt6fl6mX2Wsa6fO8Dyhuyu47PjB8nWhqtQ-rmSr95ZzeHVeOV-GMKL_ZPwu3J&amp;k=6LeK0qMpAAAAADAvDC90TuAMF-Im_3CW1fw0TdBD']</value>
      <webElementGuid>772bdc7b-9be8-4b12-8adc-527e2ac545ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
